### PR TITLE
Breaking change: rename envs to env

### PR DESCRIPTION
**Pull request by ehotinger**
**Purpose of the PR:**

Breaking change: rename `env` to `envs` to match pluralization on `Step` with `Task`.

### CODE REVIEW

**Comment by sajayantony** [comment]
I'm going by convention here. Docker compose and kube as well use env. Lets discuss this before going forward with this change.

**Comment by sajayantony** [comment]
The real change i want was passing in a --env-file or could have come from secret args here as an example - 
https://github.com/sajayantony/task-webapp/blob/master/task/acb.yaml#L4

**Comment by ehotinger** [comment]
@sajayantony could you make an issue for the environment file (it sounds similar to Node) and jot down your thoughts on how templating will work with it (if at all)?

**Comment by SteveLasker** [comment]
I like the env file approach as well.

**Comment by ehotinger** [comment]
@SteveLasker maybe you could make the issue / design for it?

**Comment by SteveLasker** [comment]
It's now in our backlog

**Pull request merged**
